export async function POST(req: Request) {
  try {
    const { mood, language = "English" } = await req.json()

    if (!mood) {
      return Response.json({ error: "Mood is required" }, { status: 400 })
    }

    // Mood-specific music recommendations
    const moodMusic: Record<
      string,
      Array<{
        title: string
        artist: string
        genre: string
        mood: string
        why: string
        energy: "low" | "medium" | "high"
      }>
    > = {
      good: [
        {
          title: "Walking on Sunshine",
          artist: "Katrina & The Waves",
          genre: "Pop",
          mood: "Uplifting",
          why: "A cheerful anthem that matches your positive energy.",
          energy: "high",
        },
        {
          title: "Good as Hell",
          artist: "Lizzo",
          genre: "Pop",
          mood: "Empowering",
          why: "An uplifting song celebrating self-love.",
          energy: "high",
        },
        {
          title: "Don't Stop Me Now",
          artist: "Queen",
          genre: "Rock",
          mood: "Energetic",
          why: "A powerful track full of joy and energy.",
          energy: "high",
        },
        {
          title: "Levitating",
          artist: "Dua Lipa",
          genre: "Pop",
          mood: "Uplifting",
          why: "A feel-good track perfect for your mood.",
          energy: "high",
        },
        {
          title: "Shut Up and Dance",
          artist: "Walk the Moon",
          genre: "Indie Pop",
          mood: "Fun",
          why: "A fun and energetic song to celebrate.",
          energy: "high",
        },
        {
          title: "Walking on Clouds",
          artist: "Pharrell Williams",
          genre: "Pop",
          mood: "Happy",
          why: "A light and joyful track.",
          energy: "medium",
        },
        {
          title: "Here Comes the Sun",
          artist: "The Beatles",
          genre: "Rock",
          mood: "Hopeful",
          why: "A timeless classic celebrating happiness.",
          energy: "medium",
        },
        {
          title: "Good Life",
          artist: "Kanye West ft. T-Pain",
          genre: "Hip-Hop",
          mood: "Celebratory",
          why: "A feel-good hip-hop track.",
          energy: "high",
        },
      ],
      love: [
        {
          title: "Perfect",
          artist: "Ed Sheeran",
          genre: "Pop",
          mood: "Romantic",
          why: "A beautiful love song that captures deep affection.",
          energy: "low",
        },
        {
          title: "All of Me",
          artist: "John Legend",
          genre: "Pop",
          mood: "Romantic",
          why: "A heartfelt ballad about unconditional love.",
          energy: "low",
        },
        {
          title: "Thinking Out Loud",
          artist: "Ed Sheeran",
          genre: "Pop",
          mood: "Romantic",
          why: "A tender love song perfect for romance.",
          energy: "low",
        },
        {
          title: "Make You Feel My Love",
          artist: "Adele",
          genre: "Pop",
          mood: "Tender",
          why: "A gentle and loving cover.",
          energy: "low",
        },
        {
          title: "At Last",
          artist: "Etta James",
          genre: "Jazz",
          mood: "Romantic",
          why: "A classic love song with timeless appeal.",
          energy: "low",
        },
        {
          title: "Unchained Melody",
          artist: "The Righteous Brothers",
          genre: "Soul",
          mood: "Passionate",
          why: "An iconic romantic ballad.",
          energy: "medium",
        },
        {
          title: "Your Body Is a Wonderland",
          artist: "John Mayer",
          genre: "Pop",
          mood: "Sensual",
          why: "A smooth and romantic track.",
          energy: "medium",
        },
        {
          title: "Kiss Me",
          artist: "Sixpence None the Richer",
          genre: "Alternative",
          mood: "Sweet",
          why: "A charming and romantic song.",
          energy: "low",
        },
      ],
      stressed: [
        {
          title: "Weightless",
          artist: "Marconi Union",
          genre: "Ambient",
          mood: "Calming",
          why: "A scientifically designed relaxation track.",
          energy: "low",
        },
        {
          title: "Breathe",
          artist: "Pink Floyd",
          genre: "Rock",
          mood: "Meditative",
          why: "A soothing and contemplative song.",
          energy: "low",
        },
        {
          title: "Clair de Lune",
          artist: "Claude Debussy",
          genre: "Classical",
          mood: "Peaceful",
          why: "A beautiful classical piece for relaxation.",
          energy: "low",
        },
        {
          title: "Holocene",
          artist: "Bon Iver",
          genre: "Indie",
          mood: "Serene",
          why: "A calming and atmospheric track.",
          energy: "low",
        },
        {
          title: "Nuvole Bianche",
          artist: "Ludovico Einaudi",
          genre: "Classical",
          mood: "Peaceful",
          why: "A gentle piano piece for stress relief.",
          energy: "low",
        },
        {
          title: "Weightless (Ambient Mix)",
          artist: "Marconi Union",
          genre: "Ambient",
          mood: "Relaxing",
          why: "Perfect for meditation and stress relief.",
          energy: "low",
        },
        {
          title: "Spiegel im Spiegel",
          artist: "Arvo Pärt",
          genre: "Classical",
          mood: "Tranquil",
          why: "A minimalist piece that soothes the mind.",
          energy: "low",
        },
        {
          title: "Gymnopédie No. 1",
          artist: "Erik Satie",
          genre: "Classical",
          mood: "Calm",
          why: "A timeless piece for relaxation.",
          energy: "low",
        },
      ],
      thrilling: [
        {
          title: "Eye of the Tiger",
          artist: "Survivor",
          genre: "Rock",
          mood: "Intense",
          why: "An iconic power anthem for adrenaline.",
          energy: "high",
        },
        {
          title: "Thunderstruck",
          artist: "AC/DC",
          genre: "Rock",
          mood: "Powerful",
          why: "A high-energy rock classic.",
          energy: "high",
        },
        {
          title: "Lose Yourself",
          artist: "Eminem",
          genre: "Hip-Hop",
          mood: "Intense",
          why: "A powerful motivational hip-hop track.",
          energy: "high",
        },
        {
          title: "Pump It Up",
          artist: "Endor",
          genre: "Electronic",
          mood: "Energetic",
          why: "An electrifying dance track.",
          energy: "high",
        },
        {
          title: "Kickstart My Heart",
          artist: "Mötley Crüe",
          genre: "Rock",
          mood: "Adrenaline",
          why: "A thrilling rock anthem.",
          energy: "high",
        },
        {
          title: "Supermassive Black Hole",
          artist: "Muse",
          genre: "Rock",
          mood: "Epic",
          why: "A powerful and intense rock track.",
          energy: "high",
        },
        {
          title: "Radioactive",
          artist: "Imagine Dragons",
          genre: "Alternative",
          mood: "Explosive",
          why: "A high-energy alternative rock song.",
          energy: "high",
        },
        {
          title: "Warriors",
          artist: "Imagine Dragons",
          genre: "Alternative",
          mood: "Powerful",
          why: "An epic and thrilling track.",
          energy: "high",
        },
      ],
      horror: [
        {
          title: "Thriller",
          artist: "Michael Jackson",
          genre: "Pop",
          mood: "Spooky",
          why: "The ultimate horror-themed song.",
          energy: "high",
        },
        {
          title: "Ghostemane",
          artist: "Ghostemane",
          genre: "Hip-Hop",
          mood: "Dark",
          why: "A dark and eerie hip-hop track.",
          energy: "medium",
        },
        {
          title: "Disturbia",
          artist: "Rihanna",
          genre: "Pop",
          mood: "Creepy",
          why: "A haunting pop song with dark vibes.",
          energy: "medium",
        },
        {
          title: "Werewolves of London",
          artist: "Warren Zevon",
          genre: "Rock",
          mood: "Spooky",
          why: "A classic horror-themed rock song.",
          energy: "medium",
        },
        {
          title: "Monster",
          artist: "Skillet",
          genre: "Metal",
          mood: "Dark",
          why: "A heavy and intense metal track.",
          energy: "high",
        },
        {
          title: "Bark at the Moon",
          artist: "Ozzy Osbourne",
          genre: "Rock",
          mood: "Eerie",
          why: "A classic horror rock anthem.",
          energy: "high",
        },
        {
          title: "Superstition",
          artist: "Stevie Wonder",
          genre: "Funk",
          mood: "Mysterious",
          why: "A mysterious and funky track.",
          energy: "medium",
        },
        {
          title: "Black Magic Woman",
          artist: "Santana",
          genre: "Rock",
          mood: "Dark",
          why: "A dark and mysterious rock classic.",
          energy: "medium",
        },
      ],
      business: [
        {
          title: "Don't Stop Believin'",
          artist: "Journey",
          genre: "Rock",
          mood: "Motivational",
          why: "An inspiring anthem for success.",
          energy: "high",
        },
        {
          title: "We Will Rock You",
          artist: "Queen",
          genre: "Rock",
          mood: "Powerful",
          why: "A powerful motivational rock song.",
          energy: "high",
        },
        {
          title: "Survivor",
          artist: "Destiny's Child",
          genre: "R&B",
          mood: "Empowering",
          why: "An empowering song about overcoming challenges.",
          energy: "high",
        },
        {
          title: "Started from the Bottom",
          artist: "Drake",
          genre: "Hip-Hop",
          mood: "Motivational",
          why: "An inspiring hip-hop track about success.",
          energy: "high",
        },
        {
          title: "The Winner Takes It All",
          artist: "ABBA",
          genre: "Pop",
          mood: "Triumphant",
          why: "A triumphant pop anthem.",
          energy: "medium",
        },
        {
          title: "Gonna Fly Now",
          artist: "Bill Conti",
          genre: "Rock",
          mood: "Inspiring",
          why: "The iconic Rocky theme for motivation.",
          energy: "high",
        },
        {
          title: "Hall of Fame",
          artist: "The Script ft. Will.i.am",
          genre: "Pop",
          mood: "Motivational",
          why: "An inspiring song about achievement.",
          energy: "high",
        },
        {
          title: "Champion",
          artist: "Fall Out Boy",
          genre: "Rock",
          mood: "Powerful",
          why: "A powerful rock anthem for winners.",
          energy: "high",
        },
      ],
      nostalgic: [
        {
          title: "Don't Stop Believin'",
          artist: "Journey",
          genre: "Rock",
          mood: "Nostalgic",
          why: "A classic 80s anthem that brings back memories.",
          energy: "high",
        },
        {
          title: "Take On Me",
          artist: "a-ha",
          genre: "Synth-Pop",
          mood: "Nostalgic",
          why: "An iconic 80s synth-pop classic.",
          energy: "medium",
        },
        {
          title: "Billie Jean",
          artist: "Michael Jackson",
          genre: "Pop",
          mood: "Nostalgic",
          why: "A timeless pop classic from the 80s.",
          energy: "high",
        },
        {
          title: "Like a Virgin",
          artist: "Madonna",
          genre: "Pop",
          mood: "Nostalgic",
          why: "An iconic 80s pop anthem.",
          energy: "high",
        },
        {
          title: "Sweet Child O' Mine",
          artist: "Guns N' Roses",
          genre: "Rock",
          mood: "Nostalgic",
          why: "A legendary 80s rock classic.",
          energy: "high",
        },
        {
          title: "Come As You Are",
          artist: "Nirvana",
          genre: "Grunge",
          mood: "Nostalgic",
          why: "A 90s grunge classic.",
          energy: "medium",
        },
        {
          title: "Wonderwall",
          artist: "Oasis",
          genre: "Rock",
          mood: "Nostalgic",
          why: "A 90s rock anthem.",
          energy: "medium",
        },
        {
          title: "Smells Like Teen Spirit",
          artist: "Nirvana",
          genre: "Grunge",
          mood: "Nostalgic",
          why: "An iconic 90s grunge song.",
          energy: "high",
        },
      ],
      curious: [
        {
          title: "Bohemian Rhapsody",
          artist: "Queen",
          genre: "Rock",
          mood: "Epic",
          why: "A complex and fascinating musical journey.",
          energy: "high",
        },
        {
          title: "Stairway to Heaven",
          artist: "Led Zeppelin",
          genre: "Rock",
          mood: "Majestic",
          why: "An epic and intricate rock masterpiece.",
          energy: "medium",
        },
        {
          title: "Comfortably Numb",
          artist: "Pink Floyd",
          genre: "Rock",
          mood: "Contemplative",
          why: "A thought-provoking and complex track.",
          energy: "medium",
        },
        {
          title: "Paranoid Android",
          artist: "Radiohead",
          genre: "Alternative",
          mood: "Experimental",
          why: "An innovative and intriguing song.",
          energy: "high",
        },
        {
          title: "Pyramid Song",
          artist: "Radiohead",
          genre: "Alternative",
          mood: "Mysterious",
          why: "A mysterious and thought-provoking track.",
          energy: "low",
        },
        {
          title: "Teardrop",
          artist: "Massive Attack",
          genre: "Electronic",
          mood: "Hypnotic",
          why: "A mesmerizing electronic composition.",
          energy: "medium",
        },
        {
          title: "Karma Police",
          artist: "Radiohead",
          genre: "Alternative",
          mood: "Intriguing",
          why: "A complex and intriguing alternative track.",
          energy: "medium",
        },
        {
          title: "Lateralus",
          artist: "Tool",
          genre: "Progressive Metal",
          mood: "Complex",
          why: "A mathematically complex and fascinating song.",
          energy: "high",
        },
      ],
      adventurous: [
        {
          title: "Born to Be Wild",
          artist: "Steppenwolf",
          genre: "Rock",
          mood: "Adventurous",
          why: "A classic adventure anthem.",
          energy: "high",
        },
        {
          title: "Highway to Hell",
          artist: "AC/DC",
          genre: "Rock",
          mood: "Daring",
          why: "A bold and adventurous rock classic.",
          energy: "high",
        },
        {
          title: "Go Your Own Way",
          artist: "Fleetwood Mac",
          genre: "Rock",
          mood: "Independent",
          why: "An inspiring song about independence.",
          energy: "high",
        },
        {
          title: "Take Me Home, Country Roads",
          artist: "John Denver",
          genre: "Country",
          mood: "Adventurous",
          why: "A song celebrating exploration and adventure.",
          energy: "medium",
        },
        {
          title: "Ventura Highway",
          artist: "America",
          genre: "Rock",
          mood: "Adventurous",
          why: "A classic road trip anthem.",
          energy: "medium",
        },
        {
          title: "Life in the Fast Lane",
          artist: "Eagles",
          genre: "Rock",
          mood: "Thrilling",
          why: "An exciting and adventurous rock song.",
          energy: "high",
        },
        {
          title: "The Wanderer",
          artist: "Dion",
          genre: "Rock",
          mood: "Adventurous",
          why: "A classic song about adventure and exploration.",
          energy: "medium",
        },
        {
          title: "Runnin' Down a Dream",
          artist: "Tom Petty",
          genre: "Rock",
          mood: "Energetic",
          why: "An energetic and adventurous rock track.",
          energy: "high",
        },
      ],
    }

    const recommendations = moodMusic[mood.toLowerCase()] || moodMusic.good

    return Response.json({ recommendations })
  } catch (error) {
    console.error("Error generating music recommendations:", error)
    return Response.json({ error: "Failed to generate recommendations" }, { status: 500 })
  }
}
